### ISSUE TITLE
Instant Crash with "DiscordAPIError: Invalid Form Body"

### ISSUE THREAD

**Issue by bluee-js** [AlexzanderFlores/WOKCommands#100]
This is the beginning of my code:
```js
module.exports = {
  aliases: ['kiss'],
  category: 'fun',
  slash: 'both',
  minArgs: 1,
  expectedArgs: '<@member or id>',
  testOnly: true,
  guildOnly: true,
  description: 'Kiss someone.',
  callback: async ({ message, args, client, instance, interaction }) => {
```

And this is the error: 
```js
bot\node_modules\discord.js\src\rest\RequestHandler.js:154
      throw new DiscordAPIError(request.path, data, request.method, res.status);
            ^

DiscordAPIError: Invalid Form Body
options[0].name: String value did not match validation regex.
    at RequestHandler.execute (bot\node_modules\discord.js\src\rest\RequestHandler.js:154:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (bot\node_modules\discord.js\src\rest\RequestHandler.js:39:14) {
  method: 'post',
  path: '/applications/824369557543059457/guilds/778011280149053460/commands',
  code: 50035,
  httpStatus: 400
}
```

Node.js: `v16.1`
Discord.js: `v12.5.3`
WOKCommands: `v1.3.5`

**Comment by bornikfik** [comment]
same issue

**Comment by bluee-js** [comment]
@bornikfik I found the solution, @ is not supported cause it's a special character, so I removed it and the command worked.

**Comment by SudryDev** [comment]
You don't provid the name:
module.exports = {
  name: "command_name",
  aliases: ['kiss'],
  category: 'fun',
  slash: 'both',
  minArgs: 1,
  expectedArgs: '<@member or id>',
  testOnly: true,
  guildOnly: true,
  description: 'Kiss someone.',
  callback: async ({ message, args, client, instance, interaction }) => {
