### ISSUE TITLE
toLowerCase not defined in slash.js

### ISSUE THREAD

**Issue by ehAsuna** [AlexzanderFlores/WOKCommands#123]
Interaction is failing here is the error. For some reason toLowerCase is not defined at SlashCommands. 
```js
(node:365) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toLowerCase' of undefined
    at SlashCommands.<anonymous> (/home/runner/ahega0/node_modules/wokcommands/dist/SlashCommands.js:63:36)
    at step (/home/runner/ahega0/node_modules/wokcommands/dist/SlashCommands.js:44:23)
    at Object.next (/home/runner/ahega0/node_modules/wokcommands/dist/SlashCommands.js:25:53)
    at /home/runner/ahega0/node_modules/wokcommands/dist/SlashCommands.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/home/runner/ahega0/node_modules/wokcommands/dist/SlashCommands.js:15:12)
    at WebSocketManager.<anonymous> (/home/runner/ahega0/node_modules/wokcommands/dist/SlashCommands.js:58:86)
    at WebSocketManager.emit (events.js:326:22)
    at WebSocketShard.onMessage (/home/runner/ahega0/node_modules/discord.js/src/client/websocket/WebSocketShard.js:296:56)
    at WebSocket.onMessage (/home/runner/ahega0/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnMessage (/home/runner/ahega0/node_modules/ws/lib/websocket.js:835:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.dataMessage (/home/runner/ahega0/node_modules/ws/lib/receiver.js:437:14)
    at Receiver.getData (/home/runner/ahega0/node_modules/ws/lib/receiver.js:367:17)
    at Receiver.startLoop (/home/runner/ahega0/node_modules/ws/lib/receiver.js:143:22)
(node:365) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
```
https://media.discordapp.net/attachments/858551519942934560/859110375328186397/unknown.png

**Comment by Assassin-1234** [comment]
#108

**Comment by ehAsuna** [comment]
What does this mean.

**Comment by pazzazzo** [comment]
https://github.com/AlexzanderFlores/WOKCommands/pull/108/files
