### ISSUE TITLE
Error : Cannot destructure property 'guildOnly' of 'command' as it is undefined.

### ISSUE THREAD

**Issue by HeduroFR** [AlexzanderFlores/WOKCommands#186]
When I start a Slash Commands, I have this issue

```cmd
 TypeError: Cannot destructure property 'guildOnly' of 'command' as it is undefined.
     at module.exports (E:\Contrats\SxnBot\node_modules\wokcommands\dist\command-checks\guild-only-check.js:4:13)
     at Client.<anonymous> (E:\Contrats\SxnBot\node_modules\wokcommands\dist\SlashCommands.js:68:33)
     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by grantgarbe** [comment]
I'm having the same exact issue.

**Comment by mcdaddytalk** [comment]
@TikoGrantYT can you provide the command you are having issues with?  I added `guildOnly: true` to one of my slash commands and I am not getting this error.
