### ISSUE TITLE
TestServers not Working

### ISSUE THREAD

**Issue by Ishu8april** [AlexzanderFlores/WOKCommands#88]
When I use the testServers Option, this error comes -
@AlexzanderFlores 
```
D:\dsc\welcomer\node_modules\discord.js\src\rest\RequestHandler.js:154
      throw new DiscordAPIError(request.path, data, request.method, res.status);
            ^

DiscordAPIError: Missing Access
    at RequestHandler.execute (D:\dsc\welcomer\node_modules\discord.js\src\rest\RequestHandler.js:154:13)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async RequestHandler.push (D:\dsc\welcomer\node_modules\discord.js\src\rest\RequestHandler.js:39:14) {
  method: 'post',
  path: '/applications/811505203606061086/guilds/835108681963798558/commands',
  code: 50001,
  httpStatus: 403
}
```

Please help me with this issue.

**Comment by Minisoft321** [comment]
I have a comment to this, i get this error when i use the "Optional" feature for expectedArgs

so here is what dosen't work
https://i.imgur.com/naQ9VQG.png

And this works.
https://i.imgur.com/4YY2o9i.png
https://i.imgur.com/cFZWjRP.png

Unless there have been a change to this, this could be one of the problems.
It worked 1 week ago or something.

**Comment by docentYT** [comment]
I found some dependence. If expectedArgs contains uppercase letters, I get this error.

**Comment by tippfehlr** [comment]
If this is still a problem maybe it is because the bot has no permissions for application commands in the guild.

Please close issues when they are not needed anymore
