### ISSUE TITLE
Crash instant

### ISSUE THREAD

**Issue by IMARCII** [AlexzanderFlores/WOKCommands#89]
root@do-s1:~/mz# node .
> MineZone is online
WOKCommands > Loaded 2 commands.
/root/mz/node_modules/discord.js/src/rest/RequestHandler.js:154
      throw new DiscordAPIError(request.path, data, request.method, res.status);
            ^

DiscordAPIError: Invalid Form Body
options[0].name: Command name is invalid
    at RequestHandler.execute (/root/mz/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async RequestHandler.push (/root/mz/node_modules/discord.js/src/rest/RequestHandler.js:39:14) {
  method: 'post',
  path: '/applications/840865486808154122/guilds/840507369222045706/commands',
  code: 50035,
  httpStatus: 400
}

**Comment by xCykrix** [comment]
@IMARCII In order to solve this issue, we would need the contents of both files in your commands directory. The error alone does not allow solving this problem. You can upload both files to a service like https://srcshare.io/ :)

**Comment by KabanFriends** [comment]
I am having exact same issue, I'd want to know a way to fix it.

The command code I used is:
```js
const rootDir = require("app-root-path");
const config = require(rootDir + '/config/config.json');

module.exports = {
    slash: true,
    testOnly: config.testMode, // Ensure you have test servers setup
    description: "Displays your name and age", // Required for slash commands
    minArgs: 2,
    expectedArgs: "<Name> <Age>",
    callback: ({ args }) => {
      // Destructure the name and age from the args array
      const [name, age] = args
  
      // The content to reply with must be returned from the callback function
      // This is required for slash commands exclusively
      return `Hello my name is ${name} and I am ${age} years old.`
    }
  }
```

**Comment by xCykrix** [comment]
Try changing expected args to `<name>` and `<age>`, as I remember hearing someone else talk about that being an issue. If that does not solve the issue, I can delve a bit deeper into looking for reasons as to why. Could also try manually setting the name `module.exports`, as the error does mention that. https://docs.wornoffkeys.com/commands/commands#object-properties

**Comment by Totto16** [comment]
According to the Discord Documentation it has to be: "Command names must be lower-case and match the regular expression ^[\w-]{1,32}$. Commands (including sub-commands) with upper- or mixed- case names will be rejected by the API with a HTTP 400 (Bad Request) response." so only lowercase, I also saw hat and added it also to the pull request #97 so that it automatically makes it lowercase and throws an error otherwise

**Comment by guyroyse** [comment]
Converting to lowercase resolved the issue for me. The example at https://docs.wornoffkeys.com/commands/slash-commands specifically uses a capital letter. Probably makes the most sense to update the documentation and close this issue.
